### ISSUE TITLE
🧐 run minimal preprocessing on all exemplars, comparing three runs

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/TheWay#10]
### Related problem

Related to https://github.com/FCP-INDI/TheWay/issues/7 and https://github.com/FCP-INDI/TheWay/issues/9

### Proposed feature

> run minimal preprocessing on all exemplars, comparing three runs: actual fMRIPrep (volume only), CPAC-fMRIPRep, and CPAC-RBC configs.  (Note please run w/ distortion correction on when maps are avail)

<a name="main-acceptance-criteria"></a>
### Acceptance criteria

- [x] all exemplars run through all pipelines
   - [x] CCNP
       - [x] transferred to ACCESS
       - [x] through fMRIPrep
       - [x] through C-PAC:fmriprep-options
       - [x] through C-PAC:rbc-options
   - [x] HBN
       - [x] ~~transferred to ACCESS~~ use from S3
       - [x] through fMRIPrep
       - [x] through C-PAC:fmriprep-options _in progress_
       - [x] through C-PAC:rbc-options _in progress_
   - [x] HRC
       - [x] transferred to ACCESS
       - [x] through fMRIPrep
       - [x] through C-PAC:fmriprep-options _in progress_
       - [x] through C-PAC:rbc-options _in progress_
   - [x] NKI
       - [x] transferred to ACCESS
       - [x] through fMRIPrep
       - [x] through C-PAC:fmriprep-options _in progress_
       - [x] through C-PAC:rbc-options _in progress_
   - [x] PNC
       - [x] transferred to ACCESS
       - [x] through fMRIPrep
       - [x] through C-PAC:fmriprep-options _in progress_
       - [x] through C-PAC:rbc-options _in progress_
- [ ] outputs compared
    - [ ] preprocessed BOLD
    - [ ] generated Schaefer-200 matrix _in progress_

### Additional context

- [x] Symlinking from `cis210040p` to `med220004p`
- [x] Before re-running `rbc-options`:
    - [x] <a name='merging-locally'></a>Merging locally (in `med220004p`)
        - [x] https://github.com/FCP-INDI/C-PAC/pull/1761
        - [x] https://github.com/FCP-INDI/C-PAC/pull/1769
        - [x] https://github.com/FCP-INDI/C-PAC/pull/1770
    - [x] Turning off nuisance regression for this round of runs (https://github.com/FCP-INDI/RBC-on-ACCESS/commit/4e4406d7e4eebf596f168c8c9450530110cd3838)

**Comment by shnizzedy** [comment]
Giving an S3 path to fMRIPrep for the positional `bids_dir` didn't work (
```Python
fmriprep: error: Path does not exist: <s3://fcp-indi/data/Projects/HBN/BIDS_curated/>
```
), so I [split the HBN run script](https://github.com/FCP-INDI/RBC-on-ACCESS/commit/333ba106ee048d9c07c547bc7ee7e34ed5c87b29#) into [a C-PAC script](https://github.com/FCP-INDI/RBC-on-ACCESS/blob/333ba106ee048d9c07c547bc7ee7e34ed5c87b29/calls/HBN_sample_run_all_C-PAC.slurm) and [an fMRIPrep script](https://github.com/FCP-INDI/RBC-on-ACCESS/blob/333ba106ee048d9c07c547bc7ee7e34ed5c87b29/calls/HBN_sample_run_all_fMRIPrep.slurm) and added 
```BASH
  aws s3 sync --no-sign-request s3://fcp-indi/data/Projects/HBN/BIDS_curated/${SUB} /ocean/projects/med220004p/shared/data_sandbox/derived/RBC-testing/data/UPenn/HBN/${SUB}
```
before giving the local path in the fMRIPrep script.
